<a href="https://colab.research.google.com/github/Francieli-Cordeiro/Francieli-Cordeiro/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
aluguel_casa = pd.read_excel("/content/housing.xlsx")
aluguel_casa.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-121.97,37.64,32.0,1283.0,194.0,485.0,171.0,60574.0,431000.0,<1H OCEAN
1,-121.99,37.61,9.0,3666.0,711.0,2341.0,703.0,46458.0,217000.0,<1H OCEAN
2,-121.97,37.57,21.0,4342.0,783.0,2172.0,789.0,46146.0,247600.0,<1H OCEAN
3,-121.96,37.58,15.0,3575.0,597.0,1777.0,559.0,57192.0,283500.0,<1H OCEAN
4,-121.98,37.58,20.0,4126.0,1031.0,2079.0,975.0,36832.0,216900.0,<1H OCEAN

In [7]:
aluguel_casa.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-118.83,34.14,16.0,1316.0,194.0,450.0,173.0,101597.0,500001.0,NEAR OCEAN
20636,-118.83,34.14,16.0,1956.0,312.0,671.0,319.0,64001.0,321800.0,NEAR OCEAN
20637,-119.00,34.08,17.0,1822.0,438.0,578.0,291.0,54346.0,428600.0,NEAR OCEAN
20638,-118.75,34.18,4.0,16704.0,2704.0,6187.0,2207.0,66122.0,357600.0,NEAR OCEAN
20639,-118.75,34.17,18.0,6217.0,858.0,2703.0,834.0,68075.0,325900.0,NEAR OCEAN

In [9]:
aluguel_casa.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [14]:
aluguel_casa = aluguel_casa.astype({"total_rooms":"int"})
aluguel_casa.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms             int64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [15]:
aluguel_casa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  int64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(8), int64(1), object(1)
memory usage: 1.6+ MB